import { NgIconsModule, provideIcons } from '@ng-icons/core';
import { featherCheck, featherX, featherAlertCircle, featherChevronDown, featherCheckCircle } from '@ng-icons/feather-icons';
import { RealTimeExpirationService } from './app/services/shared/real-time-date-expiration-check/real-time-expiration.service';
import { bootstrapApplication } from '@angular/platform-browser';
import { BrowserAnimationsModule, provideAnimations } from '@angular/platform-browser/animations';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { AppComponent } from './app/app.component';
import { provideRouter } from '@angular/router';
import { routes } from './app/app.routes';
import { Buffer } from 'buffer';
import { provideHttpClient } from '@angular/common/http';
import process from 'process';
import { importProvidersFrom } from '@angular/core';
import {
     LucideAngularModule,
     ScrollText,
     Cog,
     BanknoteArrowUp,
     BanknoteArrowDown,
     HourglassIcon,
     Trash2,
     DollarSign,
     TicketCheck,
     Check,
     Lock,
     Hourglass,
     Wallet,
     Send,
     Gem,
     ShieldCheck,
     Flag,
     Copy,
     FileTextIcon,
     ChevronDown,
     ChevronRight,
     BookOpenCheck,
     ArrowBigRight,
     RefreshCcw,
     RefreshCw,
     SplitIcon,
     Signature,
     ShieldEllipsis,
     Settings,
     CopyPlus,
     Eraser,
     GripVertical,
     Eye,
     EyeOff,
     CircleCheck,
     ShieldBan,
     CornerUpLeft,
     Sun,
     Moon,
     Inbox,
     Plus,
     ChevronUp,
     Edit2,
     CheckCircle,
     X,
     Loader,
     ShieldOff,
     ShieldCheckIcon,
     LucideImageOff,
     LockOpen,
     Search,
     Calendar,
     Wand,
     Signal,
     Link,
     Handshake,
     FileCheck,
     LucideSettings2,
     LucideLayoutTemplate,
     LucideBadgeInfo,
     LucideShuffle,
     LucidePackage,
     LucideTag,
     LucidePlus,
     LucideRefreshCcw,
     LucideNetwork,
     LucideCpu,
     LucideZap,
     LucideSparkle,
     LucideFlaskConical,
     LucideFlaskRound,
     LucideActivity,
} from 'lucide-angular';
import {
     heroPencilSquare,
     heroSquares2x2,
     heroIdentification,
     heroMinus,
     heroCheckBadge,
     heroCheck,
     heroUser,
     heroQuestionMarkCircle,
     heroInformationCircle,
     heroExclamationCircle,
     heroExclamationTriangle,
     heroUsers,
     heroCodeBracketSquare,
     heroClipboardDocumentList,
     heroArrowDownOnSquareStack,
     heroArrowTopRightOnSquare,
     heroCurrencyDollar,
     heroTrash,
     heroPlus,
     heroPlusCircle,
     heroPaperAirplane,
     heroArrowRight,
     heroTicket,
     heroClock,
     heroQueueList,
     heroArrowUturnLeft,
     heroArrowPath,
     heroUserGroup,
     heroKey,
     heroChartBar,
     heroEye,
     heroEyeSlash,
     heroAdjustmentsVertical,
     heroLockOpen,
     heroLockClosed,
     heroBanknotes,
     heroWallet,
     heroXMark,
     heroXCircle,
     heroCheckCircle,
     heroMoon,
     heroSun,
     heroCalendar,
     heroLink,
     heroLinkSlash,
     heroDocumentText,
     heroChevronUp,
     heroChevronDown,
     heroCodeBracket,
     heroFolderOpen,
     heroBars3,
     heroMagnifyingGlass,
     heroCircleStack,
     heroCog,
     heroShieldCheck,
     heroArrowUp,
     heroArrowDown,
     heroArrowsRightLeft,
     heroTag,
} from '@ng-icons/heroicons/outline';

// Make Buffer and process available globally
(globalThis as any).Buffer = Buffer;
(globalThis as any).process = process;

bootstrapApplication(AppComponent, {
     providers: [
          RealTimeExpirationService,
          provideRouter(routes),
          provideHttpClient(),
          provideAnimations(),
          provideAnimationsAsync(),
          importProvidersFrom(BrowserAnimationsModule),
          importProvidersFrom(
               LucideAngularModule.pick({
                    Cog,
                    ScrollText,
                    BanknoteArrowUp,
                    BanknoteArrowDown,
                    HourglassIcon,
                    Trash2,
                    DollarSign,
                    TicketCheck,
                    Check,
                    Lock,
                    Hourglass,
                    Wallet,
                    Send,
                    ShieldCheck,
                    Flag,
                    Copy,
                    FileTextIcon,
                    ChevronDown,
                    ChevronUp,
                    ChevronRight,
                    BookOpenCheck,
                    ArrowBigRight,
                    RefreshCcw,
                    RefreshCw,
                    SplitIcon,
                    Gem,
                    Signature,
                    ShieldEllipsis,
                    Settings,
                    CopyPlus,
                    Plus,
                    Eraser,
                    GripVertical,
                    Eye,
                    EyeOff,
                    CircleCheck,
                    ShieldBan,
                    CornerUpLeft,
                    Sun,
                    Moon,
                    Inbox,
                    Loader,
                    Edit2,
                    CheckCircle,
                    X,
                    ShieldOff,
                    LucideImageOff,
                    ShieldCheckIcon,
                    LockOpen,
                    Search,
                    Calendar,
                    Wand,
                    Signal,
                    Link,
                    FileCheck,
                    LucideSettings2,
                    LucideLayoutTemplate,
                    LucideBadgeInfo,
                    LucideShuffle,
                    LucideTag,
                    LucidePackage,
                    LucideNetwork,
                    LucideCpu,
                    LucideZap,
                    LucideSparkle,
                    LucideActivity,
                    LucideFlaskConical,
                    LucideFlaskRound,
                    LucideRefreshCcw,
                    LucidePlus,
                    Handshake,
               })
          ),
          importProvidersFrom(
               NgIconsModule.withIcons({
                    featherCheck: featherCheck,
                    featherX: featherX,
                    featherAlertCircle: featherAlertCircle,
                    featherChevronDown: featherChevronDown,
                    featherCheckCircle: featherCheckCircle,
               })
          ),
          provideIcons({
               heroDocumentText,
               heroLinkSlash,
               heroCalendar,
               heroLink,
               heroChevronUp,
               heroChevronDown,
               heroArrowUp,
               heroArrowDown,
               heroArrowsRightLeft,
               heroPencilSquare,
               heroSquares2x2,
               heroIdentification,
               heroMinus,
               heroCheckBadge,
               heroCheck,
               heroUser,
               heroTag,
               heroQuestionMarkCircle,
               heroInformationCircle,
               heroExclamationCircle,
               heroExclamationTriangle,
               heroCodeBracketSquare,
               heroUsers,
               heroClipboardDocumentList,
               heroArrowDownOnSquareStack,
               heroArrowTopRightOnSquare,
               heroCurrencyDollar,
               heroTrash,
               heroPlus,
               heroPlusCircle,
               heroPaperAirplane,
               heroArrowRight,
               heroTicket,
               heroClock,
               heroQueueList,
               heroArrowUturnLeft,
               heroArrowPath,
               heroUserGroup,
               heroKey,
               heroChartBar,
               heroEye,
               heroEyeSlash,
               heroAdjustmentsVertical,
               heroLockOpen,
               heroLockClosed,
               heroBanknotes,
               heroWallet,
               heroXMark,
               heroXCircle,
               heroCheckCircle,
               heroMoon,
               heroSun,
               heroCodeBracket,
               heroFolderOpen,
               heroBars3,
               heroMagnifyingGlass,
               heroCircleStack,
               heroCog,
               heroShieldCheck,
          }),
     ],
}).catch(err => console.error(err));
